In [2]:
import duckdb

con = duckdb.connect("health_enforcement.duckdb")
con.execute("SHOW TABLES").df()

                       name
0        dim_facility_types
1        dim_ltc_narratives
2  fact_enforcement_actions

In [ ]:
con.execute("SELECT COUNT(*) FROM fact_enforcement_actions").df()

,FACID,FACILITY_NAME,LTC,FAC_TYPE_CODE,FAC_FDR,DISTRICT_OFFICE,PENALTY_ISSUE_DATE,PENALTY_NUMBER,DISPOSITION,PENALTY_TYPE,...,TOTAL_AMOUNT_DUE_FINAL,TOTAL_PENALTY_OFFSET_AMOUNT,TOTAL_COLLECTED_AMOUNT,TOTAL_BALANCE_DUE,ACLAIMS_VISIT_NUMBER,EVENTID,DEATH_RELATED,INTAKEID_ALL,PRIORITY_ALL,SFY
0,10000060,"SEAVIEW REHABILITATION & WELLNESS CENTER, LP",LTC,SNF,Skilled Nursing Facility,Santa Rosa,2000-01-06,10001426,Closed,Citation,...,1000.0,-350.0,650.0,0.0,10010610.0,A99999,N,None,None,SFY1999-00
1,10000061,PALM DRIVE NURSING AND REHABILITATION CENTER,LTC,SNF,Skilled Nursing Facility,Santa Rosa,2000-01-26,10001435,Closed,Citation,...,7000.0,0.0,7000.0,0.0,10010652.0,A99999,N,None,None,SFY1999-00
2,10000043,PARK VIEW POST ACUTE,LTC,SNF,Skilled Nursing Facility,Santa Rosa,2000-01-26,10001436,Closed,Citation,...,1500.0,0.0,1500.0,0.0,10010654.0,A99999,N,None,None,SFY1999-00
3,10000043,PARK VIEW POST ACUTE,LTC,SNF,Skilled Nursing Facility,Santa Rosa,2000-01-27,10001437,Closed,Citation,...,1000.0,0.0,1000.0,0.0,10010657.0,A99999,N,None,None,SFY1999-00
4,10000062,"SHERWOOD OAKS POST ACUTE CARE, LLC",LTC,SNF,Skilled Nursing Facility,Santa Rosa,2000-01-28,10001438,Closed,Citation,...,1000.0,-350.0,650.0,0.0,10010659.0,A99999,N,None,None,SFY1999-00

In [6]:
con.execute("SELECT * FROM dim_ltc_narratives LIMIT 5").df()

,FACID,FACILITY_NAME,PENALTY_NUMBER,CLASS_ASSESSED_INITIAL,PENALTY_ISSUE_DATE,EVENTID,NARRATIVE LENGTH,NARRATIVE,NARRATIVE_CLEAN,TOP_KEYWORDS
0,20000132,Fremont HealthCare Center,20008964,B,01-Feb-12,V6XV11,4029,F323 483.25(h) FREE OF ACCIDENT HAZARDS/SUPERV...,F323 .(h) FREE OF ACCIDENT HAZARDS/SUPERVISION...,"skin, supervision, wound"
1,20000054,Willow Tree Nursing Center,20009068,B,02-Mar-12,K04O11,2678,Title 22 72520 (a) If a patient of a skilled n...,Title (a) If a patient of a skilled nursing ...,"discharge, bed, showed"
2,140000051,Kindred Nursing and Rehabilitation - Ygnacio V...,20009069,B,02-Mar-12,FGDY11,7868,483.12(b) (3) Permitting Resident to Return to...,.(b) () Permitting Resident to Return to Facil...,"bed, medical, care"
3,20000026,"Bay View Rehabilitation Hospital, LLC",20009078,AA,05-Mar-12,8JFW11,9084,483.25 PROVIDE CARE/SERVICES FOR HIGHEST WELL ...,. PROVIDE CARE/SERVICES FOR HIGHEST WELL BEING...,"blood, pressure, showed"
4,140000105,Lone Tree Convalescent Hospital,20009082,B,06-Mar-12,PUKB11,5560,T22 DIV5 CH3 ART3-72311(a)(1)(A) Nursing Servi...,T22 DIV5 CH3 ART3-(a)()(A) Nursing Service--Ge...,"wound, condition, showed"

In [8]:
con.execute("SELECT * FROM dim_facility_types LIMIT 5").df()

,VARIABLE,DESCRIPTION,VALUE,DEFINITION
0,FAC_TYPE_CODE,Acute Psychiatric Hospital,APH,A health facility having a duly constituted go...
1,FAC_TYPE_CODE,Adult Day Health Care,ADHC,"An organized day program of therapeutic, socia..."
2,FAC_TYPE_CODE,Ambulatory Surgical Center,ASC,Any distinct entity that operates exclusively ...
3,FAC_TYPE_CODE,Alternative Birthing Center,ABC,A clinic that is not part of a hospital and th...
4,FAC_TYPE_CODE,Chemical Dependency Recovery Hospital,CDRH,A health facility that provides 24-hour impati...